In [84]:
import numpy as np
import copy

def knapsack(weights, values, capacity):

    # knapsack

    assert len(weights) == len(values), "Lenght of values and weights must be same."

    n = len(weights)

    if n == 0:
        return 0

    val_array = np.zeros((n+1, capacity+1));

    for i in range(1, n+1):
        for j in range(1, capacity+1):
            if weights[i-1] <= j:
                val_array[i,j] = max(values[i-1] + val_array[i-1,j-weights[i-1]], val_array[i-1,j])
            else:
                val_array[i,j] = val_array[i-1,j]

    answer = []

    # back tracking

    def backtrack(i, j, chosen=[]):
        
        if i==0 and j==0:
            answer.append(chosen)

        else:

            temp_chosen = copy.deepcopy(chosen)

            c1 = []
            c2 = []

            if val_array[i-1, j] == val_array[i, j]:
                backtrack(i-1, j, temp_chosen)
            
            if val_array[i-1, j-weights[i-1]] == val_array[i, j] - values[i-1]:
                temp_chosen.append(i)
                backtrack(i-1, j-weights[i-1], temp_chosen)

    backtrack(n, capacity, [])

    # prints
    
    print("Value Array:\n", val_array)
    print("\nOptimal Values:", val_array[-1, -1])
    print("\nSet of items that can be chosen for optimal value:", answer)

In [85]:
weights = [3, 2, 4, 5, 1]
values = [50, 40, 70, 80, 10]
capacity = 7
knapsack(weights, values, capacity)

Value Array:
 [[  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  50.  50.  50.  50.  50.]
 [  0.   0.  40.  50.  50.  90.  90.  90.]
 [  0.   0.  40.  50.  70.  90. 110. 120.]
 [  0.   0.  40.  50.  70.  90. 110. 120.]
 [  0.  10.  40.  50.  70.  90. 110. 120.]]

Optimal Values: 120.0

Set of items that can be chosen for optimal value: [[3, 1], [4, 2], [5, 3, 2]]
